const assert=require('node:assert/strict');
const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {spawn,spawnSync}=require('node:child_process');const crypto=require('node:crypto');
const Zip=require('jszip');const {DOMParser}=require('@xmldom/xmldom');
const schema=require('../js/application-schema.json');const Validation=require('../js/application-validation');
const root=path.resolve(__dirname,'..');const temp=fs.mkdtempSync(path.join(os.tmpdir(),'seaandseas-test-'));
const output=path.join(root,'test-output');fs.mkdirSync(output,{recursive:true});
const hash=spawnSync('php',['-r',"echo password_hash('Test-only-Password-938!', PASSWORD_DEFAULT);"],{encoding:'utf8'}).stdout;
const port=18000+crypto.randomInt(1000);let server;let cookie='';let csrf='';let passes=0;
function sample(all=false){
 const data={};for(const[k,s]of Object.entries(schema.fields))data[k]=s.required||all?(s.enum?.[0]||({date:'2020-01-01',email:'arjun.nair@example.test',phone:'+91 9876543210',number:k==='height_cm'?'178':'76',integer:'12',consent:'on',ifsc:'SBIN0001234',bank_code:'SBIN0001234',account:'123456789012'}[s.type])||'Submitted '+k.replaceAll('_',' ')):'';
 Object.assign(data,{full_name:'Arjun Nair',digital_signature_name:'Arjun Nair',position_applied:'2nd Officer',dob:'1992-05-18',pob:'Kochi',nationality:'Indian',marital_status:'Married',date_availability:'2026-11-01',nearest_airport:'Kochi International Airport',permanent_address:'24 Marine Road, Kochi, Kerala',kin_name:'Meera Nair',kin_relationship:'Wife',kin_address:'24 Marine Road, Kochi, Kerala',trading_areas:'Indian Ocean and Arabian Gulf',boiler_suit_size:'42 (L)',shoe_size:'UK 9',last_drawn_wages:'USD 4500/month',expected_wages:'USD 4800/month',bank_holder_name:'Arjun Nair',bank_name:'State Bank of India',signature_place:'Kochi',signature_date:'2026-10-06',passport_no:'Z1234567',passport_doi:'2020-01-01',passport_doe:'2030-01-01',passport_poi:'Kochi',cdc_indian_no:'MUM123456',indos_number:'12NL1234',us_visa_type:all?'C1/D':'None'});
 if(!all)for(const k of['medical_signoff','medical_unfit_disease','medical_addiction','medical_psychiatric','med_malaria','med_diabetes','med_epilepsy','med_nervous','med_hepatitis'])data[k]='No';
 if(all){data.medical_signoff='Yes';for(const k of['medical_unfit_disease','medical_addiction','medical_psychiatric','med_malaria','med_diabetes','med_epilepsy','med_nervous','med_hepatitis']){data[k]='Yes';data[k+'_details']='Assessed and treated; fit for duty following medical review.';}data.med_vessel_name='MV Ocean Pearl';data.med_occurrence_date='2022-02-03';data.med_description='Minor ankle injury; treated and cleared for duty.';data.nri_account_no='123456789099';}
 const family=[{fam_rel:'Wife',fam_name:'Meera Nair',fam_anniv:'2018-02-14',fam_dob:'1994-07-09',fam_ppt:'P7654321',fam_doi:'2021-01-01',fam_poi:'Kochi',fam_doe:'2031-01-01',fam_ecnr:'YES'},{fam_rel:'Child (F)',fam_name:'Anaya Nair',fam_dob:'2020-03-10'}];
 const sea=[1,2].map(n=>({sea_owner:'Ocean Fleet Management',sea_vessel:n===1?'MV Ocean Pearl':'MV Coral Wave',sea_built:'2014',sea_type:'Oil Tanker',sea_grt:'42000',sea_dwt:'75000',sea_engine:'MAN B&W',sea_bhp:'12000',sea_rank:'Second Officer',sea_from:n===1?'2025-01-01':'2024-01-01',sea_to:n===1?'2025-07-01':'2024-07-01',sea_total:'tampered client duration',sea_reason:'Contract completed'}));
 const groups={licences:[{licence_flag:'Singapore',licence_rank:'Second Officer',licence_no:'COC-SG-009',licence_doi:'2024-01-01',licence_doe:'2029-01-01',licence_poi:'Maritime and Port Authority'}],family,sea_service:sea,education:[{edu_school:'Maritime Academy Kochi',edu_from:'2009-06-01',edu_to:'2013-05-01',edu_degree:'BSc Nautical Science'}],visas:[{visa_name:'Schengen crew visa S12345',visa_doi:'2025-01-01',visa_poi:'Mumbai',visa_doe:'2027-01-01'}],certificates:[{certificate_name:'Indian STCW additional refresher',certificate_no:'REF-001',certificate_doi:'2025-02-01',certificate_doe:'2030-02-01',certificate_by:'Approved Maritime Institute'},{certificate_name:'Foreign licence – Second Officer',certificate_no:'LIC-002',certificate_doi:'2024-01-01',certificate_doe:'2029-01-01',certificate_by:'Flag Administration'}]};
 for(const[g,s]of Object.entries(schema.repeats))data[s.key]=JSON.stringify(groups[g]);return data;
}
const cv=Buffer.from('%PDF-1.4\n1 0 obj\n<< /Type /Catalog >>\nendobj\n%%EOF');
async function submit(data,key=crypto.randomUUID(),file=cv,name='Arjun_CV.pdf'){
 const body=new FormData();for(const[k,v]of Object.entries(data))body.set(k,v);body.set('application_type','full_rps_01_a');body.set('cv_file',new Blob([file],{type:'application/pdf'}),name);
 const r=await fetch('http://127.0.0.1:'+port+'/submit_application.php',{method:'POST',headers:{'Idempotency-Key':key},body});return {status:r.status,body:await r.json()};
}
async function api(route,body,token=csrf){const r=await fetch('http://127.0.0.1:'+port+'/api/'+route,{method:body?'POST':'GET',headers:{...(cookie?{Cookie:cookie}:{}),...(body?{'Content-Type':'application/json','X-CSRF-Token':token}:{})},...(body?{body:JSON.stringify(body)}:{})});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return {status:r.status,body:await r.json(),setCookie:r.headers.get('set-cookie')};}
function check(name,fn){fn();passes++;console.log('PASS '+name);}
function matrix(doc){return Array.from(doc.getElementsByTagName('w:tbl')).map(t=>Array.from(t.childNodes).filter(n=>n.nodeName==='w:tr').map(r=>Array.from(r.childNodes).filter(n=>n.nodeName==='w:tc')));}
function text(node){return Array.from(node.getElementsByTagName('w:t')).map(n=>n.textContent).join('');}
async function start(serverRoot=root){
 server=spawn('php',['-d','upload_max_filesize=10M','-d','post_max_size=12M','-S','127.0.0.1:'+port,'scripts/php-router.php'],{cwd:serverRoot,env:{...process.env,APP_ENV:'local',APPLICATION_PRIVATE_DIR:path.join(temp,'private'),ADMIN_USERNAME:'teststaff',ADMIN_PASSWORD_HASH:hash},stdio:['ignore','ignore','pipe']});
 fs.writeFileSync(path.join(temp,'server.log'),'');server.stderr.on('data',v=>fs.appendFileSync(path.join(temp,'server.log'),v));
 for(let i=0;i<50;i++){try{const r=await fetch('http://127.0.0.1:'+port+'/apply');if(r.ok)return;}catch{}await new Promise(r=>setTimeout(r,100));}throw new Error('PHP server did not start');
}
async function main(){
 await start();
 check('IIS denies legacy applicant records and QA files while allowing the public schema',()=>{const config=fs.readFileSync(path.join(root,'web.config'),'utf8');const pattern=/<rule name="Block application internals"[\s\S]*?<match url="([^"]+)"/.exec(config)[1];const deny=new RegExp(pattern,'i');for(const route of['applications_roster.json','test-output/sample-application.docx','scratch/qa.html','.env','uploads/cv.pdf','includes/application_bootstrap.php'])assert.ok(deny.test(route),route);for(const route of['js/application-schema.json','api.php','download_application.php','apply.html','admin.html'])assert.ok(!deny.test(route),route);});
 const html=fs.readFileSync(path.join(root,'apply.html'),'utf8');const repeatFields=new Set(Object.values(schema.repeats).flatMap(s=>s.fields));
 check('Every form field has a mapping',()=>{for(const m of html.matchAll(/<(?:input|select|textarea)\b[^>]*name="([^"]+)"/g)){const k=m[1];assert.ok(schema.fields[k]||repeatFields.has(k.replace(/_\d+$/,''))||['_hp_trap','cv_file'].includes(k),k);}for(const k of Object.keys(schema.fields))assert.ok(html.includes('name="'+k+'"'),k);});
 const basic=sample();check('Client validation accepts realistic optional blanks',()=>assert.deepEqual(Validation.validate(basic,schema),{}));
 const key=crypto.randomUUID();const result=await submit(basic,key);check('Applicant saved and DOCX generated',()=>{assert.equal(result.status,200,JSON.stringify(result.body));assert.equal(result.body.success,true);assert.match(result.body.refNumber,/^SS-APP-\d{4}-[A-F0-9]{12}$/);});
 let response=await fetch('http://127.0.0.1:'+port+result.body.downloadUrl);const buffer=Buffer.from(await response.arrayBuffer());fs.writeFileSync(path.join(output,'sample-application.docx'),buffer);
 const source=await Zip.loadAsync(fs.readFileSync(path.join(root,schema.template)));const generated=await Zip.loadAsync(buffer);const xml=await generated.file('word/document.xml').async('string');const doc=new DOMParser().parseFromString(xml,'text/xml');const m=matrix(doc);
 check('Correct cells, optional blanks, family, visas, wages and bank',()=>{assert.equal(text(m[1][2][1]),'Arjun Nair');assert.equal(text(m[3][4][4]),'');assert.equal(text(m[3][4][5]),'');assert.equal(text(m[1][22][1]),'Meera Nair');assert.equal(text(m[1][23][1]),'Anaya Nair');assert.equal(text(m[7][3][12]),'6M 0D');assert.equal(text(m[7][4][2]),'MV Coral Wave');assert.equal(text(m[10][6][2]),'123456789012');assert.equal(text(m[11][3][2]),'');assert.ok(xml.includes('USD 4800/month'));assert.ok(xml.includes('REF-001'));assert.ok(xml.includes('Schengen crew visa'));assert.equal(text(m[5][23][2]),'COC-SG-009');assert.ok(!xml.includes('{{'));});
 const original=new DOMParser().parseFromString(await source.file('word/document.xml').async('string'),'text/xml');
 check('Logo, headers, footers, styles, relationships and declaration preserved',()=>{const declarations=d=>Array.from(d.getElementsByTagName('w:p')).map(text).filter(t=>t.startsWith('I declare')||t.startsWith('I hereby')||t.startsWith('I understand'));assert.deepEqual(declarations(doc),declarations(original));assert.ok(xml.includes('FOR SEA &amp; SEAS SHIPPING PRIVATE LIMITED'));});
 for(const name of Object.keys(source.files).filter(n=>!source.files[n].dir&&n!=='word/document.xml'))assert.deepEqual(await generated.file(name).async('nodebuffer'),await source.file(name).async('nodebuffer'),name);
 passes++;console.log('PASS All non-document package parts are byte-identical');
 const retry=await submit(basic,key);check('Idempotent retry returns same application',()=>assert.equal(retry.body.refNumber,result.body.refNumber));
 const altered=await submit({...basic,pob:'Mumbai'},key);check('Changed retry payload rejected',()=>assert.equal(altered.status,409));
 const invalid=await submit({...basic,medical_signoff:'Yes',phone:'wrong',passport_doi:'2035-01-01',nri_ifsc_swift:'invalid-code',declaration_truth:''});check('Server rejects conditional, phone, dates and declaration errors',()=>{assert.equal(invalid.status,422);for(const k of['med_description','phone','passport_doe','nri_ifsc_swift','declaration_truth'])assert.ok(invalid.body.errors[k],k);});
 const badFile=await submit(basic,crypto.randomUUID(),Buffer.from('not a pdf'));check('Spoofed CV rejected',()=>assert.equal(badFile.status,422));
 const tooMany=await submit({...basic,sea_service_json:JSON.stringify(Array(11).fill(JSON.parse(basic.sea_service_json)[0]))});check('More than ten vessels rejected',()=>assert.equal(tooMany.status,422));
 let unauth=await api('admin/applications');check('Unauthenticated staff API rejected',()=>assert.equal(unauth.status,401));
 const directUrl=route=>'http://127.0.0.1:'+port+'/api.php?route='+encodeURIComponent(route);
 let direct=await fetch(directUrl('admin/me'));check('Direct PHP staff endpoint denies unauthenticated requests',()=>assert.equal(direct.status,401));
 const incorrect=await api('admin/login',{username:'teststaff',password:'Incorrect-password'});check('Incorrect staff password is rejected',()=>assert.equal(incorrect.status,401));
 const login=await api('admin/login',{username:'teststaff',password:'Test-only-Password-938!'});csrf=login.body.csrf;check('Staff password hash and HttpOnly session authentication',()=>{assert.equal(login.status,200);assert.ok(cookie);assert.ok(csrf);assert.match(login.setCookie,/HttpOnly/i);assert.match(login.setCookie,/SameSite=Strict/i);});
 const listing=await api('admin/applications');const id=listing.body.items[0].id;check('Search/list contains no passport, bank, medical data or tokens',()=>{assert.equal(listing.body.total,1);assert.ok(!JSON.stringify(listing.body).includes('Z1234567'));assert.ok(!('downloadToken'in listing.body.items[0]));});
 direct=await fetch(directUrl('admin/applications')+'&search=Arjun',{headers:{Cookie:cookie}});check('Direct PHP staff route retains authentication and search query',()=>{assert.equal(direct.status,200);});assert.equal((await direct.json()).total,1);
 const detail=await api('admin/applications/'+id);check('Complete structured data securely retained',()=>{assert.equal(detail.body.application.rawData.family_json.length,2);assert.equal(detail.body.application.rawData.sea_service_json[0].sea_total,'6M 0D');assert.equal(detail.body.application.rawData.certificates_json.length,2);assert.equal(detail.body.application.rawData.licences_json[0].licence_no,'COC-SG-009');});
 const csrfFail=await api('admin/applications/'+id+'/status',{status:'shortlisted'},'');check('CSRF-free mutation denied',()=>assert.equal(csrfFail.status,403));
 const status=await api('admin/applications/'+id+'/status',{status:'shortlisted'});check('Authorized review update succeeds',()=>assert.equal(status.status,200));
 const download=await fetch('http://127.0.0.1:'+port+'/api/admin/applications/'+id+'/download/docx',{headers:{Cookie:cookie}});check('Staff DOCX download works',()=>assert.equal(download.status,200));
 direct=await fetch(directUrl('admin/applications/'+id+'/download/docx'),{headers:{Cookie:cookie}});check('Direct PHP staff DOCX download works',()=>assert.equal(direct.status,200));
 for(const route of['/data/applications.db','/storage/applications/test.docx','/uploads/cv.pdf','/includes/application_bootstrap.php','/.env','/NEW-APPLICATION-FORMAT-1.docx','/applications_roster.json','/test-output/sample-application.docx','/scratch/qa.html']){const r=await fetch('http://127.0.0.1:'+port+route);assert.equal(r.status,403,route);}passes++;console.log('PASS Private routes are blocked');
 const full=sample(true);check('Client validates every mapped populated field',()=>assert.deepEqual(Validation.validate(full,schema),{}));const fullResult=await submit(full);check('Full template application submitted',()=>assert.equal(fullResult.status,200,JSON.stringify(fullResult.body)));
 const fullBuffer=Buffer.from(await(await fetch('http://127.0.0.1:'+port+fullResult.body.downloadUrl)).arrayBuffer());fs.writeFileSync(path.join(output,'full-application.docx'),fullBuffer);
 const fullZip=await Zip.loadAsync(fullBuffer);const fullDoc=new DOMParser().parseFromString(await fullZip.file('word/document.xml').async('string'),'text/xml');const fullMatrix=matrix(fullDoc);
 check('Every mapped scalar lands in its exact cell',()=>{for(const[k,s]of Object.entries(schema.fields)){if(!s.cell||!full[k])continue;const[t,originalRow,c]=s.cell;let r=originalRow;for(const spec of Object.values(schema.repeats))if(spec.table===t&&originalRow>=spec.start+spec.capacity)r+=Math.max(0,JSON.parse(full[spec.key]).length-spec.capacity);const v=s.type==='date'?new Date(full[k]).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}).replaceAll(' ','-'):full[k];assert.ok(text(fullMatrix[t][r][c]).includes(v),k+' -> '+text(fullMatrix[t][r][c]));}});
 const overflow=sample();overflow.family_json=JSON.stringify(Array.from({length:6},(_,i)=>({...JSON.parse(basic.family_json)[0],fam_name:'Family member '+(i+1)})));overflow.education_json=JSON.stringify(Array.from({length:5},(_,i)=>({...JSON.parse(basic.education_json)[0],edu_school:'Maritime school '+(i+1)})));const over=await submit(overflow);check('Family and education overflow supported',()=>assert.equal(over.status,200,JSON.stringify(over.body)));const overZip=await Zip.loadAsync(Buffer.from(await(await fetch('http://127.0.0.1:'+port+over.body.downloadUrl)).arrayBuffer()));const overXml=await overZip.file('word/document.xml').async('string');check('Overflow records in cloned rows are not lost',()=>{assert.ok(overXml.includes('Family member 6'));assert.ok(overXml.includes('Maritime school 5'));});fs.writeFileSync(path.join(output,'overflow-application.docx'),await overZip.generateAsync({type:'nodebuffer'}));
 const last=await api('admin/logout',{});check('Logout invalidates staff session',()=>assert.equal(last.status,200));assert.equal((await api('admin/me')).status,401);passes++;
 const max=sample();max.sea_service_json=JSON.stringify(Array.from({length:10},(_,i)=>({...JSON.parse(basic.sea_service_json)[0],sea_vessel:'Vessel '+(i+1)})));const maxResult=await submit(max);check('Ten vessels accepted',()=>assert.equal(maxResult.status,200));
 const expiredHash=crypto.createHash('sha256').update(maxResult.body.downloadUrl.split('token=')[1]).digest('hex');
 spawnSync('php',['-r',"$d=new PDO('sqlite:'.$argv[1]);$s=$d->prepare('UPDATE applications SET download_expires=1 WHERE download_hash=?');$s->execute([$argv[2]]);",path.join(temp,'private','applications.sqlite'),expiredHash]);
 const expired=await fetch('http://127.0.0.1:'+port+maxResult.body.downloadUrl);check('Expired capability cannot download',()=>assert.equal(expired.status,404));
 const stopped=new Promise(r=>server.once('exit',r));server.kill();await stopped;
 const deployment=path.join(temp,'deployment');fs.mkdirSync(deployment);
 for(const file of['includes','phpmailer','scripts','migrations','js','submit_application.php','api.php','download_application.php','apply.html'])fs.cpSync(path.join(root,file),path.join(deployment,file),{recursive:true});
 const setupEnv={...process.env,APP_ENV:'local',APPLICATION_PRIVATE_DIR:path.join(temp,'setup-private')};delete setupEnv.ADMIN_USERNAME;delete setupEnv.ADMIN_PASSWORD_HASH;
 const originalSettings='MAIL_HOST=mail.example.test\nMAIL_PASSWORD=existing-test-mail-password\nADMIN_USERNAME=\nADMIN_PASSWORD_HASH=\n';fs.writeFileSync(path.join(deployment,'.env'),originalSettings);
 const setup=spawnSync('php',['scripts/configure-local-admin.php','--local'],{cwd:deployment,env:setupEnv,encoding:'utf8'});
 const configured=fs.readFileSync(path.join(deployment,'.env'),'utf8');const newPassword=/New password \(shown only now\): ([a-f0-9]{32})/.exec(setup.stdout)?.[1];
 check('Local setup preserves mail settings and stores only a generated password hash',()=>{assert.equal(setup.status,0,setup.stderr);assert.ok(configured.includes('MAIL_PASSWORD=existing-test-mail-password'));assert.ok(newPassword);assert.ok(!configured.includes(newPassword));assert.ok(configured.includes("ADMIN_USERNAME='crewing'"));assert.ok(configured.includes('ADMIN_PASSWORD_HASH=\''));});
 const repeatSetup=spawnSync('php',['scripts/configure-local-admin.php','--local'],{cwd:deployment,env:setupEnv,encoding:'utf8'});
 check('Local setup does not rotate existing credentials',()=>{assert.equal(repeatSetup.status,0,repeatSetup.stderr);assert.equal(fs.readFileSync(path.join(deployment,'.env'),'utf8'),configured);assert.ok(!repeatSetup.stdout.includes('New password'));});
 const productionSetup=spawnSync('php',['scripts/configure-local-admin.php','--local'],{cwd:deployment,env:{...setupEnv,APP_ENV:'production'},encoding:'utf8'});
 check('Local setup refuses production configuration',()=>{assert.equal(productionSetup.status,1);assert.equal(fs.readFileSync(path.join(deployment,'.env'),'utf8'),configured);});
 // Exercise missing configuration without binding another server or touching real .env.
 const missingAdmin=spawnSync('php',['-r',"$_GET['route']='admin/login';$_SERVER['REQUEST_METHOD']='POST';require 'api.php';"],{cwd:deployment,env:{...setupEnv,ADMIN_USERNAME:'',ADMIN_PASSWORD_HASH:'',APPLICATION_PRIVATE_DIR:''},encoding:'utf8'});
 check('Unconfigured login explains setup failure before database initialization',()=>assert.match(JSON.parse(missingAdmin.stdout).error,/Staff sign-in has not been configured/));
 const missingStorage=spawnSync('php',['-r',"$_GET['route']='admin/login';$_SERVER['REQUEST_METHOD']='POST';require 'api.php';"],{cwd:deployment,env:{...setupEnv,ADMIN_USERNAME:'teststaff',ADMIN_PASSWORD_HASH:hash,APPLICATION_PRIVATE_DIR:''},encoding:'utf8'});
 check('Missing private storage has a clear staff login error',()=>assert.match(JSON.parse(missingStorage.stdout).error,/Private application storage has not been configured/));
 await start(deployment);const failureKey=crypto.randomUUID();const failed=await submit(basic,failureKey);check('Missing template is a failure, never a success',()=>{assert.equal(failed.status,503);assert.equal(failed.body.success,false);});
 const dbPath=path.join(temp,'private','applications.sqlite');
 const query=sql=>spawnSync('php',['-r',"$d=new PDO('sqlite:'.$argv[1]);echo json_encode($d->query($argv[2])->fetchAll(PDO::FETCH_ASSOC));",dbPath,sql],{encoding:'utf8'}).stdout;
 check('Generation failure has a recoverable failed record and no files',()=>{const rows=JSON.parse(query("SELECT id,status,cv_path,docx_path FROM applications WHERE status='failed'"));assert.equal(rows.length,1);assert.equal(rows[0].cv_path,null);assert.equal(rows[0].docx_path,null);assert.ok(!fs.existsSync(path.join(temp,'private','files',rows[0].id)));});
 fs.copyFileSync(path.join(root,schema.template),path.join(deployment,schema.template));const recovered=await submit(basic,failureKey);check('Same-key retry recovers failed generation',()=>assert.equal(recovered.status,200,JSON.stringify(recovered.body)));
 fs.chmodSync(path.join(temp,'private','files'),0o500);const storageFail=await submit(basic);fs.chmodSync(path.join(temp,'private','files'),0o700);check('Storage failure reports failure and keeps consistent state',()=>assert.equal(storageFail.status,503));
 fs.chmodSync(dbPath,0o000);const dbFail=await submit(basic);fs.chmodSync(dbPath,0o600);check('Database failure reports service error, never success',()=>assert.equal(dbFail.status,503));
 const abandoned=JSON.parse(query("SELECT id FROM applications WHERE status='failed' LIMIT 1"))[0].id;
 spawnSync('php',['-r',"$d=new PDO('sqlite:'.$argv[1]);$s=$d->prepare(\"UPDATE applications SET status='processing',updated_at='2000-01-01' WHERE id=?\");$s->execute([$argv[2]]);",dbPath,abandoned]);
 const recovery=spawnSync('php',['scripts/recover-applications.php'],{cwd:deployment,env:{...process.env,APPLICATION_PRIVATE_DIR:path.join(temp,'private')},encoding:'utf8'});check('Recovery command resolves abandoned processing',()=>{assert.equal(recovery.status,0,recovery.stderr);assert.equal(JSON.parse(query("SELECT status FROM applications WHERE id='"+abandoned+"'"))[0].status,'failed');});
 check('Audit history records completion and failures without applicant payload',()=>{const events=JSON.parse(query('SELECT event FROM application_audit')).map(r=>r.event);assert.ok(events.includes('submitted'));assert.ok(events.includes('generation_or_storage_failed'));assert.ok(events.includes('abandoned_processing_recovered'));});
 console.log('\n'+passes+' checks passed. QA documents: test-output/. Runtime data: '+temp);
}
(async()=>{const z=await Zip.loadAsync(fs.readFileSync(path.join(root,schema.template)));fs.writeFileSync('/tmp/seaandseas-original.xml',await z.file('word/document.xml').async('string'));try{await main();}finally{server?.kill();}})().catch(e=>{console.error(e);console.error('PHP logs:',path.join(temp,'server.log'));process.exitCode=1;});
